const babySupplies = [
  // ==============================================================================
  // 1. 먹이기 (수유 & 이유식) - 총 20개
  // ==============================================================================
  // [분유 수유 & 세척·소독]
  {
    id: "bs_f_1",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "분유 제조기 / 분유메이커",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "버튼 하나로 조유 시간과 수고를 대폭 줄여주는 맘마존 필수 가전. 사용 기간(약 6~12개월)이 짧아 당근 거래가 매우 활발합니다.",
    momcafe1st: "베이비브레짜 포뮬러 프로 어드밴스드",
    top1: "베이비브레짜 포뮬러 프로 어드밴스드 자동 분유제조기",
    top2: "버버(BurrBurr) 스마트 분유제조기 2세대",
    top3: "콤비 스마트 분유제조기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_2",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "분유 포트 & 티포트",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "100°C 안심 가열 후 설정한 보온 온도(40~45°C)로 24시간 유지해 주는 맘마존 필수품. 매일 마시는 물이므로 새제품 구매 권장.",
    momcafe1st: "릴리프 한경희 스마트 분유포트",
    top1: "릴리프 한경희 스마트 보온 분유포트 1.5L",
    top2: "보르르 안심 유리 분유포트 1.7L",
    top3: "쿠첸 프리미엄 분유포트 티메이커",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_3",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "휴대용 분유포트 & 보온병",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "외출, 병원 방문, 여행 시 차량이나 야외에서 바로 조유할 수 있는 무선 보온 보조 가전.",
    momcafe1st: "봄봄 휴대용 무선 분유포트",
    top1: "봄봄 무선 휴대용 배터리 분유포트",
    top2: "모윰 프리미엄 원터치 안심 보온병 500ml",
    top3: "써모스 베이비 진공 단열 조유 보온병",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_4",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "분유 교반기 (분유 쉐이커)",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "분유 뭉침과 거품 발생을 최소화하여 영아 배앓이를 줄여주는 자동 쉐이커 보조 용품.",
    momcafe1st: "베이비맥스 자동 분유 쉐이커",
    top1: "베이비맥스 자동 분유 쉐이커 2세대",
    top2: "마더케이 전동 분유 교반기 쉐이커",
    top3: "이지스마트 휴대용 분유 믹서",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_5",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "젖병 소독기 (UV / 열풍)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "세척한 젖병, 쪽쪽이, 치발기, 장난감까지 UV 살균 및 열풍 건조. 돌 이후 이유식기 살균까지 오래 사용하므로 신품/핫딜 추천.",
    momcafe1st: "유팡 플러스 LED 젖병소독기",
    top1: "유팡 플러스 LED 젖병소독기 UP911",
    top2: "스펙트라 UV LED 젖병소독기",
    top3: "해님 4세대 스마트 UV 젖병소독기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_6",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "젖병 세척기",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "매일 쏟아지는 젖병 세척 부담을 줄여주는 자동 세척·스팀·열풍 살균 가전.",
    momcafe1st: "꿈비 3in1 스마트 젖병세척기",
    top1: "꿈비 스마트 젖병세척기 올인원",
    top2: "마더케이 전동 젖병 세척기",
    top3: "베베앙 젖병 자동 세척 살균기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_7",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "젖병 건조대 / 집게 / 세척솔 / 세제",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "회전형 실리콘 세척솔과 1종 젖병 전용 세제, 대용량 건조대 세트. 위생 소모품으로 신품 필수.",
    momcafe1st: "마더케이 실리콘 젖병 브러쉬 세트",
    top1: "마더케이 에코 실리콘 젖병 브러쉬 2종 세트",
    top2: "그로미미 대용량 젖병 건조대",
    top3: "블랑101 1종 젖병세정제 무향",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_8",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "소형 젖병 (150~160ml)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "신생아기 수유량(60~120ml)에 맞춘 배앓이 방지 젖병. 초기 2~4개로 시작해 아기 적합 여부 확인 후 추가 권장.",
    momcafe1st: "헤겐 배앓이방지 PPSU 젖병 150ml",
    top1: "더블하트 모유실감 3세대 젖병 160ml",
    top2: "헤겐 배앓이방지 PPSU 젖병 150ml",
    top3: "닥터브라운 옵션스플러스 젖병 150ml",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_9",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "중대형 젖병 (240~270ml)",
    period: "#영아",
    purchaseTag: "#새제품",
    description: "수유량이 늘어나는 2~3개월 이후부터 돌까지 주력으로 사용하는 대용량 젖병.",
    momcafe1st: "더블하트 모유실감 3세대 240ml",
    top1: "더블하트 모유실감 3세대 PPSU 젖병 240ml",
    top2: "헤겐 수유 젖병 240ml 2입 세트",
    top3: "스펙트라 올뉴 PA 젖병 260ml",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_10",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "신생아용 젖꼭지 (SS / S 사이즈)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "입천장과 잇몸 자극 없는 실리콘 꼭지. 위생 및 변형 우려로 중고 절대 불가, 2~3개월 주기 교체 필수.",
    momcafe1st: "더블하트 모유실감 젖꼭지 SS",
    top1: "더블하트 모유실감 3세대 젖꼭지 SS/S 2입",
    top2: "모윰 리얼핏 젖꼭지 1단계 (신생아용)",
    top3: "헤겐 배앓이방지 젖꼭지 1단계",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_11",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "노리개 젖꼭지 (쪽쪽이)",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "빨기 욕구 충족 및 등센서 발동 시 수면 유도용 필수템. 아기 구강 구조에 맞춰 1~2개 소량 구매 후 선호도 확인.",
    momcafe1st: "필립스 아벤트 울트라에어 쪽쪽이",
    top1: "필립스 아벤트 울트라에어 야광 쪽쪽이 2입",
    top2: "빕스(BIBS) 데 루스 천연고무 쪽쪽이",
    top3: "모윰 마카롱 실리콘 쪽쪽이 1단계",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_12",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "분유 수유 & 세척·소독",
    title: "쪽쪽이 클립 / 보관 케이스",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "외출이나 수면 중 쪽쪽이가 바닥에 떨어지지 않도록 옷에 고정하고 위생 보관하는 소품.",
    momcafe1st: "모윰 실리콘 쪽쪽이 클립",
    top1: "모윰 원터치 실리콘 쪽쪽이 클립 2P",
    top2: "마더케이 쪽쪽이 휴대용 케이스",
    top3: "베베락 실리콘 쪽쪽이 스트랩",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [수유 보조 & 모유 수유]
  {
    id: "bs_f_13",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "수유 보조 & 모유 수유",
    title: "수유쿠션 & 수유시트",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "수유 시 아기 각도를 45도로 잡아주어 역류를 막고 엄마 손목과 허리를 지켜주는 보조 용품. 커버 분리 세탁 가능해 당근도 인기.",
    momcafe1st: "알프레미오 친환경 수유시트 + 유비맘 수유쿠션",
    top1: "알프레미오 친환경 오가닉 수유시트",
    top2: "유비맘 C자형 수유쿠션 D-30",
    top3: "마더스베이비 메모리폼 C자형 수유쿠션",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_14",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "수유 보조 & 모유 수유",
    title: "유축기 (전동 / 휴대용)",
    period: "#신생아",
    purchaseTag: "#당근",
    description: "모유 수유 및 젖몸살 방지를 위한 유축기. 보건소 대여도 가능하며 흡입기/호스 등 소모품만 새것으로 교체해 사용 권장.",
    momcafe1st: "스펙트라 Dual-S / 와이드 유축기",
    top1: "스펙트라 Dual-S 듀얼 전동 유축기",
    top2: "스펙트라 와이드 전동 유축기 본체세트",
    top3: "시밀레 프리에 핸즈프리 웨어러블 무선 유축기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_15",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "수유 보조 & 모유 수유",
    title: "모유저장팩 & 수유패드",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "유축한 모유를 위생적으로 냉장/냉동 보관하는 이지컷 팩과 산모 모유 샘 방지 일회용 순면 패드.",
    momcafe1st: "마더케이 이지컷 모유저장팩",
    top1: "마더케이 이지컷 모유저장팩 200ml 120매",
    top2: "란시노 모유보관팩 50매",
    top3: "더블하트 허니콤 일회용 수유패드 132매",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_16",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "수유 보조 & 모유 수유",
    title: "유두 보호 크림 (라놀린 크림)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "초기 직수 시 발생하는 유두 상처 및 갈라짐을 진정시키는 순수 100% 천연 라놀린 성분 크림. 닦아내지 않고 수유 가능.",
    momcafe1st: "란시노 HPA 라놀린 유두보호 크림",
    top1: "란시노 HPA 라놀린 유두보호 크림 40g",
    top2: "메델라 퓨어란 100 라놀린 크림",
    top3: "마더스베이비 내추럴 유두보호 버터크림",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [이유식 & 성장 준비]
  {
    id: "bs_f_17",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "이유식 & 성장 준비",
    title: "유아용 하이체어 (식탁의자)",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "생후 5~6개월 이유식 시작 시 바른 앉은 자세를 유도하는 의자. 수년 이상 길게 쓰는 메인 가구로 백화점/공식몰 새제품 선호.",
    momcafe1st: "스토케 트립트랩 하이체어",
    top1: "스토케 트립트랩 하이체어 베이비세트",
    top2: "아가드 아이슬라이드 하이체어",
    top3: "본베베 점보 하이체어",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_18",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "이유식 & 성장 준비",
    title: "이유식 턱받이 (실리콘 / 방수)",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "음식물받이 포켓이 깊고 세척이 간편한 식품용 실리콘 방수 턱받이.",
    momcafe1st: "베이비뵨 소프트 턱받이",
    top1: "베이비뵨 스몰 베이비 빕 실리콘 턱받이 2P",
    top2: "도노도노 올인원 실리콘 턱받이",
    top3: "모윰 실리콘 포켓 턱받이",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_19",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "이유식 & 성장 준비",
    title: "이유식 식기 & 흡착볼",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "식탁에 강력 밀착되어 엎지름을 방지하는 실리콘 소재 안전 이유식 볼/플레이트.",
    momcafe1st: "블루마마 모두아이 흡착식판",
    top1: "블루마마 도자기 실리콘 흡착볼 세트",
    top2: "모윰 실리콘 흡착 이유식기",
    top3: "도노도노 모듈러 실리콘 식기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_f_20",
    category: "1. 먹이기 (수유 & 이유식)",
    section: "이유식 & 성장 준비",
    title: "이유식 스푼 & 큐브 보관 용기",
    period: "#영아",
    purchaseTag: "#새제품",
    description: "아기 잇몸에 부드러운 초기 실리콘 숟가락과 토핑 이유식을 소분 냉동하는 큐브 용기.",
    momcafe1st: "릿첼 첫걸음 이유식 스푼 + 글라스락 큐브",
    top1: "릿첼 소프트 유아용 이유식 스푼 케이스세트",
    top2: "마더케이 실리콘 이유식 큐브트레이",
    top3: "글라스락 베이비 이유식 눈금 보관용기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // ==============================================================================
  // 2. 재우기 & 쉬기 (수면 & 공간·놀이) - 총 25개
  // ==============================================================================
  // [수면 & 가구·섬유]
  {
    id: "bs_s_1",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "원목 / 신생아 아기침대",
    period: "#신생아",
    purchaseTag: "#당근",
    description: "부모 허리를 지켜주고 독립 수면 공간을 마련해 주는 필수 가구. 사용 기간(3~6개월)이 짧아 당근 거래 1순위.",
    momcafe1st: "벨라 원목 아기침대 / 리안 드림콧",
    top1: "벨라 원목 아기침대 풀세트",
    top2: "리안 드림콧 아기침대 이동형",
    top3: "보네스트 친환경 원목 침대",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_2",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "아기침대용 방수 쿨매트",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "태열이 많은 신생아의 체온을 낮춰주는 듀라론 냉감 쿨매트. 위생을 위해 새제품 추천.",
    momcafe1st: "포몽드 듀라론 쿨매트",
    top1: "포몽드 리버시블 듀라론 냉감 쿨매트",
    top2: "비비엔다 듀라론 쿨매트",
    top3: "도노도노 쿨에어 매쉬 쿨매트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_3",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "침대용 방수패드",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "기저귀 샘 및 분유 토사물로부터 매트리스 오염을 완벽 차단. 세탁 교체용으로 2~3장 필수.",
    momcafe1st: "비비엔다 순면 무형광 방수패드",
    top1: "비비엔다 프리미엄 순면 방수패드 L",
    top2: "말랑하니 대형 순면 방수패드",
    top3: "아가드 오가닉 방수패드",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_4",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "두상 관리 베개 (짱구베개)",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "신생아의 부드러운 두상이 납작해지는 사두증을 예방하고 통기성을 높인 인체공학 베개.",
    momcafe1st: "라비킷 라이너 루프트 두상베개",
    top1: "라비킷 라이너 루프트 메쉬 두상베개",
    top2: "지오필로우 신생아 두상베개 S",
    top3: "도노도노 에르고 두상베개",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_5",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "옆잠베개 & 뒤집기 방지 쿠션",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "모로반사를 잡고 아기가 안정적으로 옆으로 자며 통잠을 잘 수 있도록 돕는 통잠 쿠션.",
    momcafe1st: "라라스 통잠베개 / 해피테일즈 옆잠베개",
    top1: "라라스 메쉬 통잠베개",
    top2: "해피테일즈 뒤집기 방지 옆잠베개",
    top3: "달퐁 옆잠 방지 쿠션",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_6",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "역류방지쿠션 (역방쿠)",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "수유 직후 소화를 돕고 역류를 방지해 주는 등센서 방지 1등 공신. 커버는 분리 세탁하고 솜 상태 확인.",
    momcafe1st: "로토토베베 역류방지쿠션",
    top1: "로토토베베 와플 역류방지쿠션",
    top2: "제이앤제나 역류방지쿠션 밴드형",
    top3: "포그내 올인원 역류방지쿠션",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_7",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "아기 이불 & 블랭킷",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "계절 및 실내 온도에 맞는 모달/거즈 블랭킷과 가벼운 신생아 이불. 외출 시 겉싸개 대용으로도 활용.",
    momcafe1st: "도노도노 소프트 코튼 블랭킷",
    top1: "도노도노 소프트 코튼 블랭킷",
    top2: "베베데코 오가닉 와플 블랭킷",
    top3: "비비엔다 엠보 거즈 이불",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_8",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 & 가구·섬유",
    title: "아기 놀이 매트 (폴더매트 / 롤매트)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "뒤집기 및 기어 다니기 시작할 때 층간소음 방지와 안전을 위한 무독성 거실 매트.",
    momcafe1st: "알집매트 제로매트",
    top1: "알집매트 더블제로 무틈 폴더매트",
    top2: "파크론 롤매트 15T",
    top3: "꿈비 클린롤매트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [수면 보조 & 가전·환경]
  {
    id: "bs_s_9",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "백색소음기",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "엄마 자궁 소리, 빗소리, 쉬소리 등을 재현하여 수면 환경을 일정하게 유지하고 통잠을 유도하는 기기.",
    momcafe1st: "말랑하니 백색소음기",
    top1: "말랑하니 수면유도 백색소음기 프로",
    top2: "드림에그 화이트노이즈 머신",
    top3: "쿠첸 베이비 사운드 머신",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_10",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "홈캠 / 베이비캠 & 침대 거치대",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "분리 수면 및 거실 활동 시 아기 상태를 24시간 실시간 모니터링하는 고화질 홈캠.",
    momcafe1st: "헤이홈 스마트 베이비캠 Pro",
    top1: "헤이홈 스마트 베이비 홈캠 Pro + 침대거치대",
    top2: "샤오미 스마트 홈캠 C400",
    top3: "티피링크 Tapo C210 회전형 웹캠",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_11",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "수유등 / 무드등",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "야간 조유 및 기저귀 교체 시 아기 눈부심을 방지하는 무단계 미세 조광 무선 램프.",
    momcafe1st: "말랑하니 터치 무드등",
    top1: "말랑하니 충전식 LED 수유등",
    top2: "루나스퀘어 스마트 무선 수유등",
    top3: "비비라이프 실리콘 터치 무드등",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_12",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "가습기 (초음파 / 가열식)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "신생아 적정 실내 습도(50~60%)를 유지하여 태열 및 코막힘을 예방하는 세척 간편 안심 가습기.",
    momcafe1st: "조지루시 가열식 가습기 / 케어팟 스테인리스",
    top1: "조지루시 가열식 가습기 EE-DC50",
    top2: "케어팟 스테인리스 초음파 가습기 X50",
    top3: "한일 에어미스트 촉촉 가습기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_13",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "공기청정기",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "미세먼지와 털, 집먼지진드기를 정화하여 아기방 공기질을 쾌적하게 유지해 주는 필수 가전.",
    momcafe1st: "LG 퓨리케어 360도 공기청정기",
    top1: "LG전자 퓨리케어 360도 공기청정기 플러스",
    top2: "삼성전자 블루스카이 3100",
    top3: "위닉스 타워 프라임 공기청정기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_14",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "아이방 온습도계",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "적정 온도(22~24°C)와 습도(50~60%)를 상시 모니터링하는 정밀 디지털 온습도계. 거실과 침실에 각각 비치.",
    momcafe1st: "휴비딕 디지털 온습도계",
    top1: "휴비딕 온습도계 HT-1",
    top2: "샤오미 미지아 스마트 온습도계 2",
    top3: "카스 디지털 온습도계 T023",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_15",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "수면 보조 & 가전·환경",
    title: "암막 커튼 / 블라인드",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "낮잠 및 밤잠 시 빛을 완벽 차단하여 멜라토닌 분비와 안정적 수면 리듬을 만들어주는 필수 환경템.",
    momcafe1st: "아엠홈 100% 암막커튼",
    top1: "아엠홈 프리미엄 100% 방한 암막커튼",
    top2: "데코뷰 호텔식 고중량 암막커튼",
    top3: "지나송 맞춤형 이중 암막 블라인드",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [발달 놀이 & 교구·기록]
  {
    id: "bs_s_16",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "신생아 바운서",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "엄마 손을 대신해 아기를 흔들흔들 달래주고 터미타임 각도를 잡아주는 휴식 의자.",
    momcafe1st: "베이비뵨 블리스 메쉬 바운서",
    top1: "베이비뵨 바운서 블리스 메쉬",
    top2: "포맘스 락카루 스마트 자동 바운서",
    top3: "브라이트스타트 자동 바운서",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_17",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "타이니러브 모빌 / 회전 모빌",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "국민 육아템! 신생아 흑백 인형부터 2~3개월 컬러 회전 모빌까지 아기 시선을 사로잡는 마법의 장난감.",
    momcafe1st: "타이니러브 수더앤그루브 모빌",
    top1: "타이니러브 수더앤그루브 프린세스/메도우 모빌 거치대세트",
    top2: "아가드 침대 회전 모빌",
    top3: "피셔프라이스 버터플라이 모빌",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_18",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "초점책 & 아기 병풍 (흑백/컬러)",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "시각 발달 초기 흑백 대비 패턴과 2개월 이후 컬러 그림, 거울이 부착된 터미타임용 자극 병풍.",
    momcafe1st: "애플비 신생아 초점책 + 두두스토리 아기병풍",
    top1: "두두스토리 베이비 사운드 병풍 풀세트",
    top2: "애플비 신생아 초점책 4권 세트",
    top3: "블루래빗 첫 두뇌발달 초점책",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_19",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "아기 체육관 (피아노 체육관)",
    period: "#영아",
    purchaseTag: "#당근",
    description: "누워서 발로 건반을 차고 손으로 모빌을 잡으며 대근육과 청각을 자극하는 백일 전후 필수 놀잇감.",
    momcafe1st: "피셔프라이스 디럭스 피아노 아기체육관",
    top1: "피셔프라이스 킥앤플레이 피아노 아기체육관",
    top2: "하베브릭스 올인원 아기체육관",
    top3: "브라이트스타트 지글스 아기체육관",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_20",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "에듀테이블",
    period: "#영아, #유아",
    purchaseTag: "#당근",
    description: "누워서, 앉아서, 잡고 서서 등 성장 단계별로 1세 이상까지 오래 가지고 노는 대표 에듀 토이.",
    momcafe1st: "코나토이즈 에듀테이블",
    top1: "코나 에듀테이블 스마트 한영버전",
    top2: "피셔프라이스 스마트 스테이지 에듀테이블",
    top3: "하베브릭스 변신 에듀테이블",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_21",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "움직이는 사운드 토이 (꼬꼬맘 등)",
    period: "#영아",
    purchaseTag: "#새제품",
    description: "음악에 맞춰 춤추고 도망가며 아기의 터미타임과 기어가기를 유도하는 국민 사운드 장난감.",
    momcafe1st: "아임오 댄싱 꼬꼬맘",
    top1: "아임오 춤추는 꼬꼬맘 미니꼬꼬 포함",
    top2: "브이텍 깜짝볼 스마트 토이",
    top3: "피셔프라이스 춤추는 비트보",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_22",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "튤립 사운드북 / 동요 사운드북",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "손잡이를 쥐고 흔들면 불빛과 신나는 동요가 흘러나와 외출 시 카시트나 유모차에서도 달래기 최고.",
    momcafe1st: "스마트베어 튤립 사운드북",
    top1: "스마트베어 튤립 사운드북 베스트 5종 세트",
    top2: "블루래빗 첫 동요 사운드북",
    top3: "핑크퐁 아기상어 사운드북",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_23",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "치발기 (손목형 / 실리콘)",
    period: "#영아",
    purchaseTag: "#새제품",
    description: "이앓이 시기 잇몸 가려움을 해소하고 빨기 욕구를 채워주는 손목 착용 실리콘 치발기.",
    momcafe1st: "모윰 포니 / 보헴 손목 치발기",
    top1: "모윰 포니 실리콘 치발기 스탠딩형",
    top2: "마마스템 잼잼몬스터 손목 치발기",
    top3: "앙쥬 바나나 치발기 케이스세트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_24",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "애착인형",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "포근한 촉감으로 정서적 안정감과 분리불안을 줄여주는 세탁 용이 오가닉 토끼/곰 애착인형.",
    momcafe1st: "젤리캣 바니 M 애착인형",
    top1: "젤리캣 블라썸 버니 M 사이즈",
    top2: "블루래빗 오가닉 코튼 애착인형",
    top3: "메리마망 수제 오가닉 인형",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_s_25",
    category: "2. 재우기 & 쉬기 (수면 & 공간·놀이)",
    section: "발달 놀이 & 교구·기록",
    title: "디데이 달력 & 아기 다이어리",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "생후 D+1부터 100일, 돌까지 기념 촬영 소품 및 아기 발달 기록장.",
    momcafe1st: "말랑하니 우드 디데이 달력",
    top1: "말랑하니 감성 원목 디데이 달력",
    top2: "달퐁 포토 디데이 캘린더",
    top3: "리틀포레 아기 성장 기록 다이어리",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // ==============================================================================
  // 3. 씻기 & 케어 (위생·건강 & 의류) - 총 25개
  // ==============================================================================
  // [기저귀 교체 & 위생 가구]
  {
    id: "bs_c_1",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "기저귀 교체 & 위생 가구",
    title: "기저귀 갈이대 (소베맘 등)",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "출산 후 부모의 허리와 무릎을 보호해 주는 기저귀 케어 가구. 4~6개월 사용하므로 당근 추천 1위.",
    momcafe1st: "소베맘 기저귀갈이대 3단",
    top1: "소베맘 스마트 폴딩 기저귀 갈이대 세트",
    top2: "아가드 멀티 기저귀갈이대",
    top3: "베베앙 높이조절 기저귀교환대",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_2",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "기저귀 교체 & 위생 가구",
    title: "기저귀 갈이대용 방수매트",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "갈이대 매트 오염 방지 및 휴대용 외출 기저귀 패드로 활용.",
    momcafe1st: "말랑하니 휴대용 기저귀 방수매트",
    top1: "말랑하니 접이식 기저귀교환 방수패드",
    top2: "비비엔다 갈이대용 방수요",
    top3: "베베데코 오가닉 방수매트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_3",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "기저귀 교체 & 위생 가구",
    title: "기저귀 전용 매직 쓰레기통",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "이중 밀폐로 여름철 기저귀 냄새와 벌레를 완벽 차단하는 연속 리필 쓰레기통.",
    momcafe1st: "이지캔 / 매직캔 히포 2",
    top1: "매직캔 히포2 오토 실링 휴지통 27L",
    top2: "이지캔 스마트 기저귀 쓰레기통 27L",
    top3: "샤오미 스마트 센서 자동 밀폐 쓰레기통",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_4",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "기저귀 교체 & 위생 가구",
    title: "이동식 트롤리 (수납 카트)",
    period: "#전체",
    purchaseTag: "#당근",
    description: "기저귀, 손수건, 로션, 체온계를 담아 거실과 침실을 오가며 쓰는 이동식 3단 수납함.",
    momcafe1st: "이케아 로스코그 / 코스트코 3단 트롤리",
    top1: "이케아 RASKOG 로스코그 이동식 카트 3단",
    top2: "한샘 샘키즈 이동식 수납 트롤리",
    top3: "코스트코 3단 메탈 서랍 트롤리",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_5",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "기저귀 교체 & 위생 가구",
    title: "신생아 기저귀 (밴드형 NB / 1단계)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "신생아 배꼽 보호 홈이 있는 부드러운 순면 기저귀. 아기 체중에 맞춰 1~2팩씩 소량 준비.",
    momcafe1st: "하기스 네이처메이드 1단계",
    top1: "하기스 네이처메이드 밴드형 1단계 신생아용",
    top2: "팸퍼스 스와들러 1단계",
    top3: "나비잠 울트라씬 코튼 기저귀 NB",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [목욕 & 세면·스킨케어]
  {
    id: "bs_c_6",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "아기 목욕 욕조 (목욕용 + 헹굼용 2개)",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "신생아는 씻기는 물과 헹구는 물 2통이 필요. 배수구와 온도 센서가 있는 콤팩트 욕조 추천.",
    momcafe1st: "온다베이비 아기욕조 + 슈너글 욕조",
    top1: "온다베이비 신생아 욕조 2종 세트",
    top2: "슈너글 아기욕조 샴푸버디 세트",
    top3: "네이처리빙 스마트 인체공학 욕조",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_7",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "아기 세면대 수전 및 필터",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "세면대 물줄기 각도를 올려 아기 엉덩이를 바로 씻길 수 있는 회전 수전과 녹물 차단 필터.",
    momcafe1st: "워터웰 / 바디럽 세면대 아기수전",
    top1: "워터웰 360도 회전 아기 세면대 수전 필터세트",
    top2: "바디럽 퓨어썸 세면대용 필터 수전",
    top3: "대림바스 디클린 아기전용 세면대 헤드",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_8",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "아기 비데",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "세면대에 거치하여 아기를 눕힌 채 손쉽게 엉덩이를 씻겨주는 육아 필수템.",
    momcafe1st: "포브베베 아기비데 / 치코 아기비데",
    top1: "포브 프리아 아기비데 세면대 거치형",
    top2: "치코 베이비비데",
    top3: "아가드 이지 힙 클린 아기비데",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_9",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "탕온도계",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "신생아 목욕 적정 수온(38~40°C)을 실시간 체크해 주는 방수 디지털 온도계.",
    momcafe1st: "드레텍 디지털 탕온도계",
    top1: "드레텍 방수 디지털 탕온도계 오리형",
    top2: "카스 스마트 탕온도계",
    top3: "피죤 디지털 안전 탕온도계",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_10",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "신생아 올인원 바스 & 샴푸",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "눈 시림 없는 순한 약산성 거품 펌프형 헤어&바디 올인원 워시.",
    momcafe1st: "아토앤오투 옥시젠 탑투토 워시",
    top1: "아토앤오투 옥시젠 버블 탑투토 바스앤샴푸",
    top2: "몽디에스 바스앤드샴푸 400ml",
    top3: "차앤맘 피토세라마이드 헤어앤바디워시",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_11",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "아기 로션 & 고보습 크림 & 수딩젤",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "태열 진정 수딩젤과 매일 바르는 보습 로션, 침독/건조 부위 집중 고보습 크림 세트.",
    momcafe1st: "아토팜 MLE 크림 & 수딩젤",
    top1: "아토팜 MLE 베이비 크림 160ml",
    top2: "몽디에스 아토 로션 + 수딩젤 세트",
    top3: "바이오더마 에이비씨덤 보습 로션",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_12",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "목욕 & 세면·스킨케어",
    title: "기저귀 발진 연고 (비판텐) & 유두크림",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "스테로이드 없는 덱스판테놀 성분 비상 연고. 엉덩이 짓무름, 침독, 산모 유두 상처에 필수 상비약.",
    momcafe1st: "바이엘 비판텐 연고",
    top1: "바이엘 비판텐 연고 30g/100g",
    top2: "란시노 라놀린 수유 케어 크림",
    top3: "수도크림 베이비 발진 진정 크림",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [건강 & 위생 케어]
  {
    id: "bs_c_13",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "귀체온계 (브라운 체온계)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "소아과 표준! 정확하고 빠른 1초 측정 체온계. 가품 주의하여 정품 공식 수입 신품 권장.",
    momcafe1st: "브라운 써모스캔 IRT-6520",
    top1: "브라운 써모스캔 귀체온계 IRT-6520 정품 필터포함",
    top2: "휴비딕 비접촉 듀얼 체온계",
    top3: "보령 비접촉 피부적외선 체온계",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_14",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "전동 콧물 흡입기 (노시부 등)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "환절기 및 감기 시 코막힘을 시원하게 해결해 주는 육아 구원템. 노즐만 교체하면 신생아부터 어린이까지 사용.",
    momcafe1st: "노시부 프로 전동 콧물흡입기",
    top1: "노시부 프로 전동식 의료용 코세척 흡인기",
    top2: "휴비딕 전동 콧물흡입기 크린노즈",
    top3: "모윰 전동 흡인기 베이비노즈",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_15",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "네일트리머 (전동 손톱갈이) & 손톱깎이 세트",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "신생아의 종이처럼 얇은 손톱에 살이 찝히지 않도록 안전하게 갈아주는 전동 트리머와 미니 가위.",
    momcafe1st: "아가드 네일트리머 풀세트",
    top1: "아가드 루미 전동 네일트리머 세트",
    top2: "더블하트 신생아 손톱가위 세트",
    top3: "마더케이 베이비 네일케어 4종 키트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_16",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "아기 면봉 & 안전 집게 & 멸균 거즈",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "귀/코/배꼽 위생 관리를 위한 안전 스파이럴 면봉, 실리콘 코딱지 집게, 구강 멸균 거즈.",
    momcafe1st: "마더케이 점착면봉 & 안전위생집게",
    top1: "마더케이 신생아 안전 면봉 300P + 안전 집게",
    top2: "더블하트 오일 점착 면봉 50입",
    top3: "비앤비 멸균 구강 티슈 거즈 30매",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_17",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "소독용 에탄올 솜 (배꼽 소독용)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "조리원 퇴소 후 탯줄이 떨어질 때까지 하루 1~2회 배꼽 주변을 안전하게 소독하는 개별 포장 알코올 스왑.",
    momcafe1st: "그린제약 알콜스왑 100매",
    top1: "그린제약 일회용 에탄올 솜 스왑 100매",
    top2: "닥터스왑 알콜스왑 200매",
    top3: "신신제약 에탄올 소독스왑",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_18",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "건강 & 위생 케어",
    title: "아기 비타민D & 유산균 드롭",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "모유/분유 수유아의 뼈 발달과 장 건강을 위한 1일 권장량 드롭형 영양제.",
    momcafe1st: "바이오가이아 프로텍티스 베이비드롭",
    top1: "바이오가이아 프로텍티스 베이비드롭 비타민D",
    top2: "닥터바이오 D 드롭스",
    top3: "락피도 베이비 드롭스 유산균",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [의류 & 섬유·세탁]
  {
    id: "bs_c_19",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "배냇저고리 (순면 / 모달)",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "출생 직후 한 달간 입는 첫 옷. 태열 방지 60수 순면/모달 소재로 3~5벌 준비.",
    momcafe1st: "밤부베베 순한대나무 배냇저고리",
    top1: "밤부베베 시그니처 대나무 배냇저고리 3종",
    top2: "아가방 오가닉 배냇저고리 세트",
    top3: "압소바 텐셀 배냇저고리",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_20",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "신생아 바디수트 & 실내 내의",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "기저귀 교체가 쉬운 전면 스냅 단추형 바디수트와 계절별 실내 순면 내의.",
    momcafe1st: "유니클로 베이비 메쉬 바디수트",
    top1: "유니클로 베이비 코튼메쉬 바디수트 2P",
    top2: "아가방 무형광 순면 긴팔 바디수트",
    top3: "베베드피노 실내 상하의 세트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_21",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "속싸개 & 스와들업 / 수면조끼",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "나비잠 자세를 유지해 모로반사를 막고 통잠을 재워주는 지퍼형 스와들업과 겉싸개 대용 속싸개.",
    momcafe1st: "러브투드림 스와들업 오리지널",
    top1: "러브투드림 스와들업 오리지널 S/M",
    top2: "에이든 순면 모슬린 속싸개 3종",
    top3: "말랑하니 지퍼형 이지 스와들",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_22",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "손싸개, 발싸개, 아기 모자",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "얼굴 긁힘 방지 손싸개와 체온 조절용 골지 발싸개, 딸꾹질 멈춤용 꼭지 모자.",
    momcafe1st: "밤부베베 손싸개 & 오가닉 모자",
    top1: "밤부베베 대나무 손싸개 2P + 발싸개 2P",
    top2: "아가방 오가닉 아기모자 세트",
    top3: "블루독베이비 손발싸개 기프트세트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_23",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "거즈 & 엠보 손수건 / 천기저귀",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "침 닦기/수유용 거즈 30장, 목욕 타월/엉덩이 닦기용 엠보 20장, 다용도 속싸개/타월용 천기저귀 5장 필수.",
    momcafe1st: "밤부베베 시그니처 거즈 & 엠보 손수건",
    top1: "밤부베베 시그니처 대나무 거즈 손수건 30매",
    top2: "밤부베베 순한 대나무 엠보 손수건 20매",
    top3: "도노도노 순면 천기저귀 5P 세트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_24",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "아기 옷걸이 & 서랍장",
    period: "#전체",
    purchaseTag: "#당근",
    description: "어깨 늘어남 없는 미니 논슬립 아기 전용 옷걸이와 E0 등급 친환경 아기 옷 수납 서랍장.",
    momcafe1st: "한샘 샘키즈 수납장 + 마더케이 옷걸이",
    top1: "한샘 샘키즈 수납장 1305",
    top2: "마더케이 논슬립 베이비 옷걸이 30P",
    top3: "리빙앤유 슬림 유아 옷걸이",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_c_25",
    category: "3. 씻기 & 케어 (위생·건강 & 의류)",
    section: "의류 & 섬유·세탁",
    title: "아기 전용 세탁세제 & 섬유유연제",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "알레르기 유발 물질 없는 무향·식물성 계면활성제 안심 세제. 출산 전 모든 아기옷 빨래에 필수.",
    momcafe1st: "블랑101 고농축 아기세제",
    top1: "블랑101 시그니처 고농축 아기 세탁세제 1L",
    top2: "레드루트 유기농 베이비 세탁세제",
    top3: "하우파파 안심 중성 아기세제",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // ==============================================================================
  // 4. 외출 & 이동 - 총 15개
  // ==============================================================================
  // [유모차 & 탑승 용품]
  {
    id: "bs_o_1",
    category: "4. 외출 & 이동",
    section: "유모차 & 탑승 용품",
    title: "디럭스 / 절충형 유모차",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "신생아 뇌 흔들림을 방지하는 서스펜션과 양대면 기능 탑재. 사용 기간 1년 안팎이라 당근 거래 1순위.",
    momcafe1st: "부가부 폭스5 / 실버크로스 듄",
    top1: "부가부 폭스 5 디럭스 유모차",
    top2: "실버크로스 듄 컴팩트 디럭스",
    top3: "에그2 럭셔리 유모차",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_2",
    category: "4. 외출 & 이동",
    section: "유모차 & 탑승 용품",
    title: "휴대용 유모차 (원터치 폴딩)",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "생후 6개월 이후부터 4~5세까지 매일 쓰는 가볍고 기내 반입 가능한 유모차. 오래 쓰므로 신품 권장.",
    momcafe1st: "부가부 버터플라이 / 줄즈 에어플러스",
    top1: "부가부 버터플라이 휴대용 유모차",
    top2: "줄즈 에어 플러스 기내반입 유모차",
    top3: "해밀턴 X1 플러스 오토폴딩 유모차",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_3",
    category: "4. 외출 & 이동",
    section: "유모차 & 탑승 용품",
    title: "유모차 라이너 / 통풍 쿨시트",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "땀띠 예방용 무선 송풍 팬 내장 사계절 통풍 시트와 머리 흔들림 방지 에어라이너.",
    momcafe1st: "폴레드 에어러브 4 오레오 통풍시트",
    top1: "폴레드 에어러브4 롤리팝 통풍 쿨시트",
    top2: "도노도노 사계절 양면 유모차 라이너",
    top3: "베베누보 에어 매쉬 쿨시트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_4",
    category: "4. 외출 & 이동",
    section: "유모차 & 탑승 용품",
    title: "유모차 모빌 / 컵홀더 & 오거나이저 가방",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "외출 시 아기 시선을 끄는 클립형 모빌과 휴대폰, 텀블러, 물티슈를 바로 꺼내는 유모차 걸이백.",
    momcafe1st: "부가부 오거나이저 + 타이니러브 유모차 모빌",
    top1: "타이니러브 뮤지컬 네이처스트롤 유모차 모빌",
    top2: "부가부 정품 컵홀더",
    top3: "루시 스마트 유모차 오거나이저 가방",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_5",
    category: "4. 외출 & 이동",
    section: "유모차 & 탑승 용품",
    title: "휴대용 손선풍기 (안전망 유모차 선풍기)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "문어발 삼각대 다리로 유모차 안전바에 고정하고 아기 손가락이 들어가지 않는 미세 그물망 안전 팬.",
    momcafe1st: "오아 삼각대 유모차 선풍기",
    top1: "오아 문어발 무선 유모차 선풍기",
    top2: "프롬비 휴대용 아기 안전망 선풍기",
    top3: "루메나 FAN PRO4 무선 선풍기",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [카시트 & 차량 안전]
  {
    id: "bs_o_6",
    category: "4. 외출 & 이동",
    section: "카시트 & 차량 안전",
    title: "바구니 카시트",
    period: "#신생아",
    purchaseTag: "#당근",
    description: "조리원 퇴소 및 예방접종 병원 이동 시 필수. 사용 기간이 100일 미만으로 짧아 깨끗한 당근 구매 적극 추천.",
    momcafe1st: "페도라 C0+ / 싸이벡스 아톤 바구니카시트",
    top1: "싸이벡스 아톤 S2 바구니 카시트",
    top2: "페도라 C0 플러스 신생아 바구니카시트",
    top3: "맥시코시 카브리오픽스 바구니카시트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_7",
    category: "4. 외출 & 이동",
    section: "카시트 & 차량 안전",
    title: "회전형 아이소픽스(ISOFIX) 카시트",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "360도 회전으로 승하차가 쉽고 최신 i-Size 안전 인증을 받은 장기 필수 장비. 안전과 AS를 위해 반드시 신품 구매.",
    momcafe1st: "브라이텍스 듀얼픽스 아이사이즈",
    top1: "브라이텍스 듀얼픽스 플러스 i-Size 회전형",
    top2: "다이치 올인원 360 카시트",
    top3: "싸이벡스 제로나 Gi i-Size 카시트",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_8",
    category: "4. 외출 & 이동",
    section: "카시트 & 차량 안전",
    title: "차량용 후방 베이비 거울",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "운전석 룸미러로 뒷좌석 뒤보기 카시트에 탄 아기의 호흡과 상태를 실시간 확인하는 광각 안전 거울.",
    momcafe1st: "폴레드 와이드 베이비 뷰 미러",
    top1: "폴레드 차량용 와이드 베이비 뷰 미러",
    top2: "다이치 프리미엄 차량용 후방거울",
    top3: "벤츠 아기 후방 확인 볼록거울",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_9",
    category: "4. 외출 & 이동",
    section: "카시트 & 차량 안전",
    title: "차량용 햇빛가리개 (암막 선쉐이드)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "창문 자외선을 차단해 카시트 탄 아기의 시력을 보호하고 숙면을 유도하는 자석형/정전기 암막 쉐이드.",
    momcafe1st: "베베데코 자석형 차량 햇빛가리개",
    top1: "베베데코 프리미엄 자석 암막 차량용 햇빛가리개",
    top2: "도노도노 자외선 차단 3중 암막 쉐이드",
    top3: "아가드 정전기 흡착 차량용 커튼",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [아기띠 & 슬링]
  {
    id: "bs_o_10",
    category: "4. 외출 & 이동",
    section: "아기띠 & 슬링",
    title: "신생아 밀착 아기띠 / 슬링",
    period: "#신생아, #영아",
    purchaseTag: "#당근",
    description: "생후 1개월부터 100일까지 목을 가누지 못하는 아기를 밀착해 감싸 안아주고 재우는 가벼운 슬링.",
    momcafe1st: "베이비뵨 미니 코튼/메쉬",
    top1: "베이비뵨 베이비 캐리어 미니 3D 메쉬",
    top2: "코니 아기띠 플렉스 엘라스트",
    top3: "포그내 스텝원 에어 슬링 아기띠",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_11",
    category: "4. 외출 & 이동",
    section: "아기띠 & 슬링",
    title: "올인원 힙시트 아기띠",
    period: "#영아, #유아",
    purchaseTag: "#새제품",
    description: "목 가누고 몸무게가 늘어나는 100일 이후부터 장시간 외출 시 부모 허리/골반 부담을 줄여주는 힙시트 결합형.",
    momcafe1st: "포그내 맥스 올인원 아기띠",
    top1: "포그내 맥스 라이트 올인원 아기띠",
    top2: "에르고베이비 옴니 브리즈 360",
    top3: "아이엔젤 닥터다이얼 올인원 아기띠",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_12",
    category: "4. 외출 & 이동",
    section: "아기띠 & 슬링",
    title: "아기띠 침받이 & 턱받이 패드",
    period: "#영아",
    purchaseTag: "#새제품",
    description: "아기띠 어깨끈을 빠는 아기 침으로부터 섬유를 보호하고 위생적으로 교체 세탁하는 순면 패드.",
    momcafe1st: "베이비뵨 정품 아기띠 턱받이",
    top1: "베이비뵨 캐리어 미니 전용 턱받이 2P",
    top2: "포그내 오가닉 어깨 침받이 2P",
    top3: "밤부베베 대나무 아기띠 침받이",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },

  // [외출 의류 & 보조 가방]
  {
    id: "bs_o_13",
    category: "4. 외출 & 이동",
    section: "외출 의류 & 보조 가방",
    title: "신생아 겉싸개 / 외출 블랭킷",
    period: "#신생아",
    purchaseTag: "#새제품",
    description: "병원 및 조리원 퇴소 시 외부 찬바람으로부터 신생아 체온을 보호해 주는 필수 보온 감싸개.",
    momcafe1st: "아가방 포근 순면 겉싸개",
    top1: "아가방 보송 사계절 겉싸개",
    top2: "압소바 순면 엠보 겉싸개",
    top3: "베베데코 오가닉 구름 겉싸개",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_14",
    category: "4. 외출 & 이동",
    section: "외출 의류 & 보조 가방",
    title: "퇴소용 우주복 / 외출복 & 풋모자",
    period: "#신생아, #영아",
    purchaseTag: "#새제품",
    description: "퇴소 날이나 예방접종 외출 시 입히는 발싸개 일체형 방한 우주복 및 풋모자.",
    momcafe1st: "블루독베이비 퇴소용 본딩 우주복",
    top1: "블루독베이비 신생아 보닛모자 + 우주복 세트",
    top2: "밍크뮤 플라워 본딩 외출 우주복",
    top3: "에뜨와 신생아 파일 우주복",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  },
  {
    id: "bs_o_15",
    category: "4. 외출 & 이동",
    section: "외출 의류 & 보조 가방",
    title: "기저귀 가방 (백팩 / 숄더백 / 이너백)",
    period: "#전체",
    purchaseTag: "#새제품",
    description: "분유 보온병 포켓, 방수 포켓, 기저귀 패드가 구비되어 양손이 자유로운 초경량 기저귀 백팩.",
    momcafe1st: "제이해밀턴 기저귀가방 백팩 L4",
    top1: "제이해밀턴 프리미엄 기저귀 백팩 L4",
    top2: "마더케이 올인원 기저귀 숄더백",
    top3: "포브 콤팩트 기저귀 이너백 가방",
    top1_url: "https://link.coupang.com/a/hDXnz86Thk",
    top2_url: "https://link.coupang.com/a/hDXnz86Thk",
    top3_url: "https://link.coupang.com/a/hDXnz86Thk"
  }
];

module.exports = babySupplies;
