[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host " [MaternityBag] Multi-PC Setup / Environment Config" -ForegroundColor Yellow
Write-Host "==========================================================" -ForegroundColor Cyan

$currentUser = $env:USERNAME
Write-Host "[Info] Current User: $currentUser" -ForegroundColor Gray

$candidates = @(
    $env:ANDROID_HOME,
    $env:ANDROID_SDK_ROOT,
    "C:\Users\$currentUser\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "D:\Android\Sdk"
)

$foundSdk = $null
foreach ($path in $candidates) {
    if ($path -and (Test-Path $path)) {
        $foundSdk = $path
        break
    }
}

if ($foundSdk) {
    Write-Host "[OK] Detected Android SDK: $foundSdk" -ForegroundColor Green
    
    $escaped = $foundSdk.Replace('\', '\\').Replace(':', '\:')
    $timeStr = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    
    $content = "## Auto-generated by setup_environment`r`n## User: $currentUser`r`n## Date: $timeStr`r`nsdk.dir=$escaped`r`n"
    $propPath = Join-Path $PSScriptRoot "local.properties"
    [System.IO.File]::WriteAllText($propPath, $content, [System.Text.Encoding]::UTF8)
    
    Write-Host "----------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "[SUCCESS] local.properties has been updated for $currentUser!" -ForegroundColor Green
    Write-Host "You can now open the project in Android Studio." -ForegroundColor White
} else {
    Write-Host "[NOTICE] Android SDK was not found on this PC." -ForegroundColor Yellow
    Write-Host "         (Android Studio / SDK not yet installed on this PC)" -ForegroundColor Gray
    Write-Host "----------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "[TIP] You can still run and preview the full app right now!" -ForegroundColor Cyan
    Write-Host "      Double-click '앱_미리보기_실행.bat' to open the preview in your browser." -ForegroundColor Cyan
    Write-Host "----------------------------------------------------------" -ForegroundColor DarkGray
}

Write-Host "`nSetup completed." -ForegroundColor Gray
